services:
  redis:
    image: redis:7-alpine
    container_name: xm-exam-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    command: --config /livekit.yaml
    restart: unless-stopped
    ports:
      - "7880:7880"
      - "7881:7881"
      - "50000-50020:50000-50020/udp"
    volumes:
      - ./livekit/livekit.yaml:/livekit.yaml:ro

volumes:
  redis-data:
